### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by zddhub** [zddhub/opensse#10]
Reported by @warmhug

Follow the doc of https://github.com/zddhub/opensse/wiki/How-to-train-data , when I run `extract` command, it throws errors:
```sh
$ sse extract -d ~/Database/SHREC12/ -f ~/Database/SHREC12/2012_filelist -o ~/Database/SHREC12/2012_
dyld: Library not loaded: @rpath/libopencv_core.3.2.dylib
  Referenced from: /usr/local/bin/extract
  Reason: image not found
```
My installation directory are `/usr/local/opt/opencv3/include`(actually in`/usr/local/Cellar/opencv3/HEAD-c1007c7/include`) and `/usr/local/Cellar/boost/1.63.0/include/boost`, they are homebrew's directory. 

Is this error because my installation directory is not appropriate?

**Comment by zddhub** [comment]
Please add opencv library (like as libopencv_core.3.2.dylib) to your library path

**Comment by warmhug** [comment]
Done. But may encounter some new mistakes, the content of 2012_keypoints and 2012_features file are all just `0` and no more. The contents of the 2012_filelist file are empty.
```sh
$ sse extract -d ~/Database/SHREC12/ -f ~/Database/SHREC12/2012_filelist -o ~/Database/SHREC12/2012_
Extract descriptors 0/0.
```
And
```sh
$ sse vocabulary -f ~/Database/SHREC12/2012_features -n 1000 -o ~/Database/SHREC12/vocabulary
Assertion failed: (collection.size() >= numclusters), function kmeans_init_random, file /Users/hua/inner/opensse/../opensse/sse/vocabulary/kmeans_init.h, line 30.
cluster ...
```

**Comment by zddhub** [comment]
So sad! I will try that and make it work

**Comment by zddhub** [comment]
Please give `sse extract` more times (~30+ minutes ) to run, when I run it, and use `tail -f 2012_features` as below:

![image](https://cloud.githubusercontent.com/assets/6077698/24295923/f5689540-10d7-11e7-9979-3f25e2628831.png)

It means feature are extracting now.

I will print prompt info when exacting

**Comment by warmhug** [comment]
`sse extract` end Immediately. Not as your gif picture shows.

**Comment by zddhub** [comment]
Do you download the database and get 102 line drawing views for each model?

**Comment by warmhug** [comment]
Sorry, I forgot, and I get it, but the document did not say how to use it?

**Comment by zddhub** [comment]
I think i have written all things, please help update if it is not clear

**Comment by warmhug** [comment]
![image](https://zos.alipayobjects.com/rmsportal/JeZilENfWQIfuJyTvnff.png)

The question is how to use "line drawing views" with these `sse filelist / extract` commands？

**Comment by zddhub** [comment]
This is another project, you can go to its README file and use `gen_view_image` command. This command only projects one modal to 102 views images each time, perhaps you need a script to deal with more modals

**Comment by warmhug** [comment]
I follow the README file, but they have nothing to do with `sse ..` command. So I can't understand also. like `sse filelist -d ~/Database/SHREC12/ -p "*.jpg" -o ~/Database/SHREC12/2012_filelist` Where the "*.jpg" file are?

**Comment by zddhub** [comment]
I have another project to project 102 views images for each model, please link to https://github.com/zddhub/trianglemesh for detail.

`gen_view_image` is not a sub-command of sse, its usage:
`gen_view_image modelfile xfdir viewnum imagedir`

**Comment by zddhub** [comment]
How's going on? Did you fix this bug?

**Comment by warmhug** [comment]
Now it works fine, you can close this issue, thanks
