### ISSUE TITLE
How to compile on the windows without docker?

### ISSUE THREAD

**Issue by learntolearn11** [zddhub/opensse#12]

**Comment by zddhub** [comment]
I think it is the same with linux. See detail in wiki: https://github.com/zddhub/opensse/wiki/How-to-install

**Comment by learntolearn11** [comment]
Hi, when I compile the opensse.pro and SketchSearchDemo.pro, I get the error show as follow, any idea?

release\ @C:\Users\ADMINI~1\AppData\Local\Temp\nm491F.tmp
moc_trimeshview.cpp
moc_mainwindow.cpp
moc_sketcharea.cpp
moc_resultphotowidget.cpp
正在生成代码...
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\bin\SketchSearchDemo.exe @C:\Users\ADMINI~1\AppData\Local\Temp\nm57FE.tmp
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glClear，该符号在函数 "protected: void __cdecl TriMeshView::cls(void)" (?cls@TriMeshView@@IEAAXXZ) 中被引用
GLCamera.obj : error LNK2001: 无法解析的外部符号 __imp_glClear
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glClearColor，该符号在函数 "protected: void __cdecl TriMeshView::cls(void)" (?cls@TriMeshView@@IEAAXXZ) 中被引用
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glClearDepth，该符号在函数 "protected: void __cdecl TriMeshView::cls(void)" (?cls@TriMeshView@@IEAAXXZ) 中被引用
GLCamera.obj : error LNK2001: 无法解析的外部符号 __imp_glClearDepth
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glDisable，该符号在函数 "protected: void __cdecl TriMeshView::cls(void)" (?cls@TriMeshView@@IEAAXXZ) 中被引用
trimeshview_draw_lines.obj : error LNK2001: 无法解析的外部符号 __imp_glDisable
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glDisable
GLCamera.obj : error LNK2001: 无法解析的外部符号 __imp_glDisable
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glMultMatrixd，该符号在函数 "protected: virtual void __cdecl TriMeshView::paintGL(void)" (?paintGL@TriMeshView@@MEAAXXZ) 中被引用
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glPopMatrix，该符号在函数 "protected: virtual void __cdecl TriMeshView::paintGL(void)" (?paintGL@TriMeshView@@MEAAXXZ) 中被引用
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glPushMatrix，该符号在函数 "protected: virtual void __cdecl TriMeshView::paintGL(void)" (?paintGL@TriMeshView@@MEAAXXZ) 中被引用
trimeshview.obj : error LNK2019: 无法解析的外部符号 __imp_glViewport，该符号在函数 "protected: virtual void __cdecl TriMeshView::resizeGL(int,int)" (?resizeGL@TriMeshView@@MEAAXHH@Z) 中被引用
trimeshview_draw_ridges_and_valleys.obj : error LNK2019: 无法解析的外部符号 __imp_glBegin，该符号在函数 "private: void __cdecl TriMeshView::draw_ridges(class std::vector<float,class std::allocator<float> > const &,float)" (?draw_ridges@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@M@Z) 中被引用
trimeshview_draw_lines.obj : error LNK2001: 无法解析的外部符号 __imp_glBegin
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glBegin
trimeshview_draw_apparent_ridges.obj : error LNK2001: 无法解析的外部符号 __imp_glBegin
trimeshview_draw_ridges_and_valleys.obj : error LNK2019: 无法解析的外部符号 __imp_glColor4f，该符号在函数 "private: void __cdecl TriMeshView::draw_segment_ridge(int,int,int,float,float,float,float,float,float,float,bool)" (?draw_segment_ridge@TriMeshView@@AEAAXHHHMMMMMMM_N@Z) 中被引用
trimeshview_draw_lines.obj : error LNK2001: 无法解析的外部符号 __imp_glColor4f
trimeshview_draw_apparent_ridges.obj : error LNK2001: 无法解析的外部符号 __imp_glColor4f
trimeshview_draw_ridges_and_valleys.obj : error LNK2019: 无法解析的外部符号 __imp_glEnd，该符号在函数 "private: void __cdecl TriMeshView::draw_ridges(class std::vector<float,class std::allocator<float> > const &,float)" (?draw_ridges@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@M@Z) 中被引用
trimeshview_draw_lines.obj : error LNK2001: 无法解析的外部符号 __imp_glEnd
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glEnd
trimeshview_draw_apparent_ridges.obj : error LNK2001: 无法解析的外部符号 __imp_glEnd
trimeshview_draw_ridges_and_valleys.obj : error LNK2019: 无法解析的外部符号 __imp_glLineWidth，该符号在函数 "private: void __cdecl TriMeshView::draw_ridges(class std::vector<float,class std::allocator<float> > const &,float)" (?draw_ridges@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@M@Z) 中被引用
trimeshview_draw_lines.obj : error LNK2001: 无法解析的外部符号 __imp_glLineWidth
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glLineWidth
trimeshview_draw_apparent_ridges.obj : error LNK2001: 无法解析的外部符号 __imp_glLineWidth
trimeshview_draw_ridges_and_valleys.obj : error LNK2019: 无法解析的外部符号 __imp_glVertex3fv，该符号在函数 "private: void __cdecl TriMeshView::draw_segment_ridge(int,int,int,float,float,float,float,float,float,float,bool)" (?draw_segment_ridge@TriMeshView@@AEAAXHHHMMMMMMM_N@Z) 中被引用
trimeshview_draw_lines.obj : error LNK2001: 无法解析的外部符号 __imp_glVertex3fv
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glVertex3fv
trimeshview_draw_apparent_ridges.obj : error LNK2001: 无法解析的外部符号 __imp_glVertex3fv
trimeshview_draw_lines.obj : error LNK2019: 无法解析的外部符号 __imp_glBlendFunc，该符号在函数 "private: void __cdecl TriMeshView::draw_silhouette(class std::vector<float,class std::allocator<float> > const &)" (?draw_silhouette@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@@Z) 中被引用
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glBlendFunc
trimeshview_draw_lines.obj : error LNK2019: 无法解析的外部符号 __imp_glColor3f，该符号在函数 "private: void __cdecl TriMeshView::draw_boundaries(bool)" (?draw_boundaries@TriMeshView@@AEAAX_N@Z) 中被引用
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glColor3f
trimeshview_draw_lines.obj : error LNK2019: 无法解析的外部符号 __imp_glDepthMask，该符号在函数 "private: void __cdecl TriMeshView::draw_silhouette(class std::vector<float,class std::allocator<float> > const &)" (?draw_silhouette@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@@Z) 中被引用
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glDepthMask
trimeshview_draw_lines.obj : error LNK2019: 无法解析的外部符号 __imp_glEnable，该符号在函数 "private: void __cdecl TriMeshView::draw_silhouette(class std::vector<float,class std::allocator<float> > const &)" (?draw_silhouette@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@@Z) 中被引用
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glEnable
GLCamera.obj : error LNK2001: 无法解析的外部符号 __imp_glEnable
trimeshview_draw_lines.obj : error LNK2019: 无法解析的外部符号 __imp_glPointSize，该符号在函数 "private: void __cdecl TriMeshView::draw_silhouette(class std::vector<float,class std::allocator<float> > const &)" (?draw_silhouette@TriMeshView@@AEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@@Z) 中被引用
trimeshview_draw_base.obj : error LNK2001: 无法解析的外部符号 __imp_glPointSize
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glColorPointer，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glDepthFunc，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glDisableClientState，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glDrawArrays，该符号在函数 "private: void __cdecl TriMeshView::draw_normals(void)" (?draw_normals@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glDrawElements，该符号在函数 "private: void __cdecl TriMeshView::draw_strips(void)" (?draw_strips@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glEnableClientState，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glNormalPointer，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glPolygonMode，该符号在函数 "private: void __cdecl TriMeshView::draw_edges(void)" (?draw_edges@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glPolygonOffset，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glVertex2f，该符号在函数 "private: void __cdecl TriMeshView::draw_color_maps(void)" (?draw_color_maps@TriMeshView@@AEAAXXZ) 中被引用
trimeshview_draw_base.obj : error LNK2019: 无法解析的外部符号 __imp_glVertexPointer，该符号在函数 "private: void __cdecl TriMeshView::draw_base_mesh(void)" (?draw_base_mesh@TriMeshView@@AEAAXXZ) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glFrustum，该符号在函数 "public: void __cdecl GLCamera::setupGL(class Vec<3,float> const &,float)const " (?setupGL@GLCamera@@QEBAXAEBV?$Vec@$02M@@M@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glGetDoublev，该符号在函数 "private: void __cdecl GLCamera::mouse_click(int,int,class Vec<3,float> const &,float)" (?mouse_click@GLCamera@@AEAAXHHAEBV?$Vec@$02M@@M@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glGetIntegerv，该符号在函数 "public: void __cdecl GLCamera::mouse(int,int,enum Mouse::button,class Vec<3,float> const &,float,class XForm<double> &)" (?mouse@GLCamera@@QEAAXHHW4button@Mouse@@AEBV?$Vec@$02M@@MAEAV?$XForm@N@@@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glLightfv，该符号在函数 "public: void __cdecl GLCamera::setupGL(class Vec<3,float> const &,float)const " (?setupGL@GLCamera@@QEBAXAEBV?$Vec@$02M@@M@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glLoadIdentity，该符号在函数 "public: void __cdecl GLCamera::setupGL(class Vec<3,float> const &,float)const " (?setupGL@GLCamera@@QEBAXAEBV?$Vec@$02M@@M@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glMatrixMode，该符号在函数 "public: void __cdecl GLCamera::setupGL(class Vec<3,float> const &,float)const " (?setupGL@GLCamera@@QEBAXAEBV?$Vec@$02M@@M@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glReadPixels，该符号在函数 "private: bool __cdecl GLCamera::read_depth(int,int,class Vec<3,float> &)const " (?read_depth@GLCamera@@AEBA_NHHAEAV?$Vec@$02M@@@Z) 中被引用
GLCamera.obj : error LNK2019: 无法解析的外部符号 __imp_glScissor，该符号在函数 "private: bool __cdecl GLCamera::read_depth(int,int,class Vec<3,float> &)const " (?read_depth@GLCamera@@AEBA_NHHAEAV?$Vec@$02M@@@Z) 中被引用
mainwindow.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl Json::Json(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Json@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: __cdecl MainWindow::MainWindow(class QWidget *)" (??0MainWindow@@QEAA@PEAVQWidget@@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z)，该符号在函数 "void __cdecl std::_Destroy_range<struct std::_Wrap_alloc<class std::allocator<class cv::Mat_<class std::complex<double> > > > >(class cv::Mat_<class std::complex<double> > *,class cv::Mat_<class std::complex<double> > *,struct std::_Wrap_alloc<class std::allocator<class cv::Mat_<class std::complex<double> > > > &,struct std::_Nonscalar_ptr_iterator_tag)" (??$_Destroy_range@U?$_Wrap_alloc@V?$allocator@V?$Mat_@V?$complex@N@std@@@cv@@@std@@@std@@@std@@YAXPEAV?$Mat_@V?$complex@N@std@@@cv@@0AEAU?$_Wrap_alloc@V?$allocator@V?$Mat_@V?$complex@N@std@@@cv@@@std@@@0@U_Nonscalar_ptr_iterator_tag@0@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "private: char * __cdecl cv::String::allocate(unsigned __int64)" (?allocate@String@cv@@AEAAPEAD_K@Z)，该符号在函数 "public: __cdecl cv::String::String(char const *)" (??0String@cv@@QEAA@PEBD@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)，该符号在函数 "public: __cdecl cv::String::~String(void)" (??1String@cv@@QEAA@XZ) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::deallocate(void)" (?deallocate@Mat@cv@@QEAAXXZ)，该符号在函数 "void __cdecl std::_Destroy_range<struct std::_Wrap_alloc<class std::allocator<class cv::Mat_<class std::complex<double> > > > >(class cv::Mat_<class std::complex<double> > *,class cv::Mat_<class std::complex<double> > *,struct std::_Wrap_alloc<class std::allocator<class cv::Mat_<class std::complex<double> > > > &,struct std::_Nonscalar_ptr_iterator_tag)" (??$_Destroy_range@U?$_Wrap_alloc@V?$allocator@V?$Mat_@V?$complex@N@std@@@cv@@@std@@@std@@@std@@YAXPEAV?$Mat_@V?$complex@N@std@@@cv@@0AEAU?$_Wrap_alloc@V?$allocator@V?$Mat_@V?$complex@N@std@@@cv@@@std@@@0@U_Nonscalar_ptr_iterator_tag@0@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z)，该符号在函数 "public: virtual void __cdecl SketchSearcher::query(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct QueryResult,class std::allocator<struct QueryResult> > &)" (?query@SketchSearcher@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@UQueryResult@@V?$allocator@UQueryResult@@@std@@@3@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl sse::Galif::Galif(unsigned int,unsigned int,unsigned int,double,double,double,double,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int)" (??0Galif@sse@@QEAA@IIINNNN_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1I@Z)，该符号在函数 "public: __cdecl SketchSearcher::SketchSearcher(class Json &)" (??0SketchSearcher@@QEAA@AEAVJson@@@Z) 中被引用
sketchsearcher.obj : error LNK2001: 无法解析的外部符号 "public: virtual float __cdecl sse::TF_simple::operator()(class sse::InvertedIndex const &,unsigned int)const " (??RTF_simple@sse@@UEBAMAEBVInvertedIndex@1@I@Z)
sketchsearcher.obj : error LNK2001: 无法解析的外部符号 "public: virtual float __cdecl sse::IDF_simple::operator()(class sse::InvertedIndex const &,unsigned int,unsigned int,unsigned int)const " (??RIDF_simple@sse@@UEBAMAEBVInvertedIndex@1@III@Z)
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl sse::InvertedIndex::InvertedIndex(unsigned int)" (??0InvertedIndex@sse@@QEAA@I@Z)，该符号在函数 "public: __cdecl SketchSearcher::SketchSearcher(class Json &)" (??0SketchSearcher@@QEAA@AEAVJson@@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl sse::InvertedIndex::query(class std::vector<float,class std::allocator<float> > const &,class sse::TF_interface const &,class sse::IDF_interface const &,unsigned int,class std::vector<struct std::pair<float,__int64>,class std::allocator<struct std::pair<float,__int64> > > &)" (?query@InvertedIndex@sse@@QEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@AEBVTF_interface@2@AEBVIDF_interface@2@IAEAV?$vector@U?$pair@M_J@std@@V?$allocator@U?$pair@M_J@std@@@2@@4@@Z)，该符号在函数 "public: virtual void __cdecl SketchSearcher::query(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct QueryResult,class std::allocator<struct QueryResult> > &)" (?query@SketchSearcher@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@UQueryResult@@V?$allocator@UQueryResult@@@std@@@3@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl sse::InvertedIndex::query(class std::vector<float,class std::allocator<float> > const &,class sse::TF_interface const &,class sse::IDF_interface const &,unsigned int,unsigned int,class std::vector<struct std::pair<float,__int64>,class std::allocator<struct std::pair<float,__int64> > > &)" (?query@InvertedIndex@sse@@QEAAXAEBV?$vector@MV?$allocator@M@std@@@std@@AEBVTF_interface@2@AEBVIDF_interface@2@IIAEAV?$vector@U?$pair@M_J@std@@V?$allocator@U?$pair@M_J@std@@@2@@4@@Z)，该符号在函数 "public: virtual void __cdecl SketchSearcher::query(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct QueryResult,class std::allocator<struct QueryResult> > &)" (?query@SketchSearcher@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@UQueryResult@@V?$allocator@UQueryResult@@@std@@@3@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl sse::InvertedIndex::load(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?load@InvertedIndex@sse@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: __cdecl SketchSearcher::SketchSearcher(class Json &)" (??0SketchSearcher@@QEAA@AEAVJson@@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl sse::FileList::getFilename(unsigned int)const " (?getFilename@FileList@sse@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)，该符号在函数 "public: virtual void __cdecl SketchSearcher::query(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct QueryResult,class std::allocator<struct QueryResult> > &)" (?query@SketchSearcher@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@UQueryResult@@V?$allocator@UQueryResult@@@std@@@3@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl sse::FileList::load(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?load@FileList@sse@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: __cdecl SketchSearcher::SketchSearcher(class Json &)" (??0SketchSearcher@@QEAA@AEAVJson@@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "void __cdecl sse::read(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::vector<float,class std::allocator<float> >,class std::allocator<class std::vector<float,class std::allocator<float> > > > &,void (__cdecl*)(int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &),class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?read@sse@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@3@P6AXHH0@Z0@Z)，该符号在函数 "public: __cdecl SketchSearcher::SketchSearcher(class Json &)" (??0SketchSearcher@@QEAA@AEAVJson@@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl Json::getValue(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?getValue@Json@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@0@Z)，该符号在函数 "public: __cdecl SketchSearcher::SketchSearcher(class Json &)" (??0SketchSearcher@@QEAA@AEAVJson@@@Z) 中被引用
sketchsearcher.obj : error LNK2019: 无法解析的外部符号 "void __cdecl sse::quantize(class std::vector<class std::vector<float,class std::allocator<float> >,class std::allocator<class std::vector<float,class std::allocator<float> > > > const &,class std::vector<class std::vector<float,class std::allocator<float> >,class std::allocator<class std::vector<float,class std::allocator<float> > > > const &,class std::vector<float,class std::allocator<float> > &,class sse::QuantizerHard<class std::vector<float,class std::allocator<float> >,struct sse::L2norm_squared<class std::vector<float,class std::allocator<float> >,float> > &)" (?quantize@sse@@YAXAEBV?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@0AEAV?$vector@MV?$allocator@M@std@@@3@AEAV?$QuantizerHard@V?$vector@MV?$allocator@M@std@@@std@@U?$L2norm_squared@V?$vector@MV?$allocator@M@std@@@std@@M@sse@@@1@@Z)，该符号在函数 "public: virtual void __cdecl SketchSearcher::query(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct QueryResult,class std::allocator<struct QueryResult> > &)" (?query@SketchSearcher@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@UQueryResult@@V?$allocator@UQueryResult@@@std@@@3@@Z) 中被引用
..\bin\SketchSearchDemo.exe : fatal error LNK1120: 55 个无法解析的外部命令

**Comment by zddhub** [comment]
You need install QT and enable opengl
