### ISSUE TITLE
Some issues with OpenGl in Qt 5.8  

### ISSUE THREAD

**Issue by hanfengsunshine** [zddhub/opensse#13]
Requires Nvidia? 

I am using AMD

**Comment by hanfengsunshine** [comment]
![screenshot from 2017-06-19 18-46-16](https://user-images.githubusercontent.com/14012055/27282274-d2527f60-5521-11e7-8553-bee37f3f7816.png)

**Comment by zddhub** [comment]
No need Nvidia, you need check GL when you install QT.

**Comment by hanfengsunshine** [comment]
When  I install QT 5.8, there is not any GL... options

**Comment by zddhub** [comment]
Perhaps you need install libgl1-mesa-dev at first.
