### ISSUE TITLE
Train data not working 

### ISSUE THREAD

**Issue by hanfengsunshine** [zddhub/opensse#14]
![2017-06-19 21 35 43](https://user-images.githubusercontent.com/14012055/27287979-f81b47b6-5537-11e7-8b31-4a176329a744.png)
![2017-06-19 21 36 34](https://user-images.githubusercontent.com/14012055/27287997-04ffe144-5538-11e7-9f9f-0c60cabd7ece.png)

And please, why cannot train the data? Where to find the data ?

**Comment by hanfengsunshine** [comment]
Extract descriptors 0/0.?

**Comment by zddhub** [comment]
See database section and download 3D target dataset(~112MB) to your local.
