### ISSUE TITLE
Question on generate Gabor filter

### ISSUE THREAD

**Issue by EternalConfession** [zddhub/opensse#16]
Why did u use ny & nx when you generate the Gabor filter.

I'm so confused with that.

Thanks

**Comment by zddhub** [comment]
I forgot, Can you help make it better?

**Comment by EternalConfession** [comment]
I'm confused with the meaning of that code.

As it's seems to be different form the Gabor filter listed in the paper.

I'm trying to figure it out.

Best,
Jianhui

2017-07-10 20:25 GMT+08:00 zdd <notifications@github.com>:
