### ISSUE TITLE
“sse vocabulary -f features -n 1000 -o vocabulary” ? why choose the number '1000'？

### ISSUE THREAD

**Issue by StoneMa** [zddhub/opensse#19]
it seems very slow when i set 1000 as the features number， how it works？ if i choose another one what about the recall?

**Comment by zddhub** [comment]
1000 is the size of visual  vocabulary, it is an experimental value, You can refer to Mathias' paper for detail.

You can change 1000 to another one directly.

**Comment by StoneMa** [comment]
Thx
