### ISSUE TITLE
Have you ever met such a problem？

### ISSUE THREAD

**Issue by StoneMa** [zddhub/opensse#20]
![image](https://user-images.githubusercontent.com/6917909/33920465-1b61b466-dff9-11e7-96f4-7f86f6ba9a84.png)

and another question:
I can't Play with SketchSearchDemo, the window flash crash weather because of my Qt status is Expired,？

**Comment by conorcodes** [comment]
@StoneMa any idea how to fix this... I have a similar issue I think, though I am on Mac.


`>> sketch search :
>> input absolute path, like "/Users/zdd/zddhub.png"
>> type q exit
>> good luck!
>> /Users/fitzgcon/Desktop/image_finder/images/app_images/4.jpg
Assertion failed: (sample.size() == _numOfWords), function addSample, file /Users/fitzgcon/Downloads/opensse-master/opensse/index/invertedindex.cpp, line 47.
/usr/local/bin/sse: line 40:  2933 Abort trap: 6           $*`
