### ISSUE TITLE
via which port should access this server?

### ISSUE THREAD

**Issue by Torah** [zddhub/opensse#23]
Dear zdd,

Hi,
I tried to setup your opensse in my virtualmachine, but after make install success, I don't know which port to access this server? I reviewed the dockerfile and see no port there. BTW, I tried via your web version: http://online.opensse.com/ and it also seemed not working now(Figure below).
![QQ截图20190708171802](https://user-images.githubusercontent.com/6466559/60799479-c9deac00-a1a5-11e9-9391-36ffa07b5955.png)
Could you be kind enough to answer these two questions?

Cheers,
Wang

**Comment by zddhub** [comment]
The opensse is client app instead of service.

 My service for http://online.opensse.com runs out of money, and I don't think we should use this service any more.

**Comment by Torah** [comment]
So, opensr?

**Comment by zddhub** [comment]
Opensr is a client app as well, and the service version is not open source

**Comment by Torah** [comment]
good.
