### ISSUE TITLE
Linking with Boost library

### ISSUE THREAD

**Issue by vva4innovation** [zddhub/opensse#3]
Hello,

First of all thank you very much for implementing the sketch-based method. 

I have been trying to run this code in my laptop. However, I get two errors related to Boost library which I am not able to solve no matter what I do. I was wondering if you faced this problem before or know the solution to it. It would be really helpful if you can provide any directions to solve this.

I am using Qt5.5 in Ubuntu 14.04 and here is my `opensse.pri` content.

```
unix:!macx {
#I use Ubuntu
INCLUDEPATH += $$PWD \
    /usr/include

LIBS += -L/usr/lib/ \
    -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_features2d -lopencv_ml \
    -lboost_thread-mt -lboost_system-mt -lboost_thread -lboost_system -lboost_filesystem

# opencv 2.4.7 - 2.4.9 can work well.
INCLUDEPATH += $$PWD \
    /home/mycomputer/boost_1_57_0 \
    /home/mycomputer/opencv-2.4.9/include \

}
```

And when I run opensse application, I get the following errors:
*  In function `boost::thread::start_thread()`:
    * Undefined reference to `boost::thread::start_thread_noexcept()`

* In function `boost::thread::join()`:
    * Undefined reference to `boost::thread::join_noexcept()`
* collect2: error: ld returned 1 exit status

**Comment by zddhub** [comment]
It looks like boost thread lib cannot be find, I remembered in some case, only boost_thread can work, so remove -lboost_thread-mt -lboost_system-mt (or  -lboost_thread -lboost_system, don't use both)and try again.

**Comment by vva4innovation** [comment]
It is still the same.

**Comment by zddhub** [comment]
Now OpenSSE support docker, please compare your environment with docker, read README.md for detail.
