### ISSUE TITLE
error occurring  with compiling

### ISSUE THREAD

**Issue by racaljk** [zddhub/opensse#4]
For building your project, I downloaded and compiled opencv&boost, but now I  am in trouble  with building GUIDemo when linking with opencv and booat libraries
there are development environment which I build:
- windows10
- qtcreator5.0.0
- opencv 2.4.9
- boost_1_55_0

I append following text in in my opensse.pri:
```cpp
INCLUDEPATH += $$PWD \
    F:\boost_1_55_0 \
    F:\opencv\build\include 

LIBS += -LF:\opencv \
            -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_features2d -lopencv_ml\
         -LF:\boost_1_55_0\stage\lib \
            -lboost_thread -lboost_system
```
But when I built it, the qt debug output
 ```
can not find -lthread-xx
can not find ...
```
what should I do:C , I haven't used opencv and boost before

**Comment by zddhub** [comment]
Now OpenSSE support docker, please compare your environment with docker, read README.md for detail.
