### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [zddhub/opensse#5]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the destructor for the class "TriMeshView"](https://github.com/zddhub/opensse/blob/e9223e6a2a89510e413af22453bfa97a1ee71bff/gui/SketchSearchDemo/trimeshview/trimeshview.cpp#L86 "Destructor for TriMeshView").

**Comment by zddhub** [comment]
Thanks elfring, please help fix this issue and pull requests directly.
