### ISSUE TITLE
crashing on mac (reports included)

### ISSUE THREAD

**Issue by V-Go** [zddhub/opensse#7]
[issue.txt](https://github.com/zddhub/opensse/files/769488/issue.txt)

Hi i have compiled and done as mentioned with instructions applied on only one model Teddy. i receive this issue as soon as i let go of the pen tool on demo. (attached error report)

When tried with non gui tool, similar errors with a jpg format, but png format of the same file worked. Same error as the gui error report . I assume this is expected, but just included to show comparison of error with gui report.

"Assertion failed: (image.type() == CV_8UC3), function compute, file ../../../opensse-master/features/galif.cpp, line 201."

![screen shot 2017-02-12 at 17 48 49](https://cloud.githubusercontent.com/assets/9059138/22864556/8c68822c-f14b-11e6-841b-a6aca8dba59f.png)

**Comment by zddhub** [comment]
![image](https://cloud.githubusercontent.com/assets/6077698/22880467/3a81e3d6-f21d-11e6-954a-9da5446d2c4c.png)

Hi, .ong is not supported image format.

**Comment by V-Go** [comment]
Hi apologies, thats a mistake comparison then. Just the issue now is the Gui crashing with the pen tool release on first line draw

**Comment by zddhub** [comment]
This is my environment:
![image](https://cloud.githubusercontent.com/assets/6077698/22881432/6a811f9e-f221-11e6-88fd-1a04d514798b.png)

The model file Under Extended folder

**Comment by V-Go** [comment]
I don't think necessarily there's any accidental coupling with folder structure, i've tried different combinations and they seem to work without gui.

I do however receive this when compiling the sketch demo, could this be the cause?
![screen shot 2017-02-13 at 15 10 27](https://cloud.githubusercontent.com/assets/9059138/22888811/e777c28c-f1fe-11e6-9418-bf9c542092b7.png)

**Comment by V-Go** [comment]
ok fixed my issue, it was a collision of .dylibs because i used homebrew to install the requirements

Future googler reference: [https://community.alfresco.com/community/ecm/blog/2012/12/11/homebrew-share-thumbnails-and-previews-on-os-x/](url) theres a section on the page to help conflicts with Png,Tiffs,Jpegs.

Also I have also stumbled upon a coupling in your code regards to folder structure, it is assumed that all .off files are in the same folders as the line view images, this also causes the program the crash. (when after a successful search you go to click on the model)

**Comment by zddhub** [comment]
<img width="1368" alt="screen shot 2017-02-14 at 9 06 23 pm" src="https://cloud.githubusercontent.com/assets/6077698/22930382/e6e2d17a-f2fa-11e6-8697-bdf0a1089f51.png">

**Comment by zddhub** [comment]
@V-Go I reproduced the crash bug, the root cause is drawed sketch image is under the relative path, You can move this image to /tmp file. This change will also make 'open SketchSearchDemo.app' work. I have a patch to fix this issue:
https://github.com/zddhub/opensse/commit/67575e5f69035e89bd2d17483627bcc4320c027b 

The crash log as below:
"Assertion failed: (image.type() == CV_8UC3), function compute, file ../../../opensse-master/features/galif.cpp, line 201."

**Comment by V-Go** [comment]
I think you might have found another bug, I am currently re-running the image processing and am keeping the same naming convention that you have kept , to see if i can fix the "cannot find model" error. 

The Gui is working for me now, just this model loading error to go.

**Comment by V-Go** [comment]
So this is my folder structure (kept it the same as yours)

![screen shot 2017-02-14 at 16 32 32](https://cloud.githubusercontent.com/assets/9059138/22938361/7f03d9ae-f2d3-11e6-882f-3e429ae9fdbe.png)


This is what i executing

![screen shot 2017-02-14 at 16 39 13](https://cloud.githubusercontent.com/assets/9059138/22938613/3228e506-f2d4-11e6-83ad-8216817befbb.png)


This is the output - (its failing since other stages dont work because it didnt find jpegs)

![screen shot 2017-02-14 at 16 39 24](https://cloud.githubusercontent.com/assets/9059138/22938626/3c7e23b8-f2d4-11e6-8fa0-483a0328d29f.png)


Am i misunderstanding something, the filelist is a global fileslist of the entire directory right? or do i have to do a filelist for each model? 

i assumed its only 1 filelist i need to make and it worked when i just dumped all jpegs into one folder like last time, but not with this folder structure. I also tried "*/*/*.jpeg" with no luck either, am I doing something wrong?

**Comment by V-Go** [comment]
![screen shot 2017-02-14 at 21 42 25](https://cloud.githubusercontent.com/assets/9059138/22950752/97bf76bc-f2fe-11e6-8104-aee7b8a299a5.png)

Ok so heres the issue i face at the moment using the same structure you have mentioned in your example. Its looking for the wrong file name of the model file, how do you fix this?

**Comment by zddhub** [comment]
D00001view not D00001views

**Comment by V-Go** [comment]
![screen shot 2017-02-15 at 07 10 26](https://cloud.githubusercontent.com/assets/9059138/22963955/f04afa46-f34d-11e6-8aa9-062d297b6ad8.png)

Same issue still
