### ISSUE TITLE
Some installation errors

### ISSUE THREAD

**Issue by warmhug** [zddhub/opensse#9]
Follow [this](http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/) install opencv3, then run `brew install boost` to install latest version of boost 1.63.0. Then run:

```sh
mkdir release && cd release
cmake ..
make

# begin throw error

fatal error: 'opencv2/core/core.hpp' file not found
#include <opencv2/core/core.hpp>
         ^
1 error generated.
make[2]: *** [sse/CMakeFiles/opensse.dir/io/filelist.cpp.o] Error 1
make[1]: *** [sse/CMakeFiles/opensse.dir/all] Error 2
make: *** [all] Error 2
```
Then I follow [this](https://github.com/BVLC/caffe/issues/3876) add `include_directories(/usr/local/opt/opencv3/include)` to CMakeLists.txt file, run `cmake ..` and `make`, it outputs the new error as follows

```sh
[  3%] Building CXX object sse/CMakeFiles/opensse.dir/io/filelist.cpp.o
[  6%] Building CXX object sse/CMakeFiles/opensse.dir/io/reader_writer.cpp.o
[ 10%] Building CXX object sse/CMakeFiles/opensse.dir/features/util.cpp.o
[ 13%] Building CXX object sse/CMakeFiles/opensse.dir/features/generator.cpp.o
[ 16%] Building CXX object sse/CMakeFiles/opensse.dir/features/detector.cpp.o
[ 20%] Building CXX object sse/CMakeFiles/opensse.dir/features/galif.cpp.o
[ 23%] Building CXX object sse/CMakeFiles/opensse.dir/quantize/quantizer.cpp.o
[ 26%] Building CXX object sse/CMakeFiles/opensse.dir/index/tfidf.cpp.o
[ 30%] Building CXX object sse/CMakeFiles/opensse.dir/index/invertedindex.cpp.o
[ 33%] Linking CXX shared library ../lib/libopensse.dylib
ld: library not found for -lopencv_core
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopensse.dylib] Error 1
make[1]: *** [sse/CMakeFiles/opensse.dir/all] Error 2
make: *** [all] Error 2
```

What is the problem?

**Comment by zddhub** [comment]
I installed OpenCV 3.0 and boost in `/usr/local/` path, include files are under `/usr/local/include` folder and libraries are under `/usr/local/lib`.

If you install in other path, please open top CMakeLists.txt file and  change below links to your path:

```sh
include_directories(/usr/local/include)

link_directories(/usr/local/lib)
```

**Comment by warmhug** [comment]
This is partially modified of CMakeLists.txt file
```sh
include_directories(/usr/local/opt/opencv3/include /usr/local/Cellar/boost/1.63.0/include/boost)
include_directories(..)
include_directories(${PROJECT_SOURCE_DIR}/sse)

link_directories(/usr/local/opt/opencv3/lib /usr/local/Cellar/boost/1.63.0/lib)
```
And it also throw errors
```sh
......
[ 30%] Building CXX object sse/CMakeFiles/opensse.dir/index/invertedindex.cpp.o
[ 33%] Linking CXX shared library ../lib/libopensse.dylib
ld: library not found for -lboost_thread
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopensse.dylib] Error 1
make[1]: *** [sse/CMakeFiles/opensse.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by zddhub** [comment]
It seems like boost lib cannot be found, please go into '/usr/local/Cellar/boost/1.63.0/lib' folder, and make sure boost_thread exist, maybe named libboost_thread.dylib or libboost_thread-mt.dylib and change below line:


   set(REQUIRED_LIB opencv_core opencv_imgproc opencv_imgcodecs opencv_highgui opencv_features2d opencv_ml boost_thread boost_system)

**Comment by warmhug** [comment]
I change `boost_thread` to `boost_thread-mt`, It seems to be working fine. Run `make`, it outputs info as follows
```sh
......
Scanning dependencies of target test_galif
[ 90%] Building CXX object tests/CMakeFiles/test_galif.dir/test_galif/main.cpp.o
[ 93%] Linking CXX executable test_galif
[ 93%] Built target test_galif
Scanning dependencies of target stat_vocab
[ 96%] Building CXX object tests/CMakeFiles/stat_vocab.dir/stat_vocab/main.cpp.o
[100%] Linking CXX executable stat_vocab
[100%] Built target stat_vocab
```
Thanks and suggest you can update the wiki document for this situation.

**Comment by zddhub** [comment]
This is why I am working on removing boost from core OpenSSE library. It is hard to remove OpenCV, I added docker support to make life happy

**Comment by warmhug** [comment]
Follow the doc of https://github.com/zddhub/opensse/wiki/How-to-train-data , when I run `extract` command, it throws errors:
```sh
$ sse extract -d ~/Database/SHREC12/ -f ~/Database/SHREC12/2012_filelist -o ~/Database/SHREC12/2012_
dyld: Library not loaded: @rpath/libopencv_core.3.2.dylib
  Referenced from: /usr/local/bin/extract
  Reason: image not found
```
My installation directory are `/usr/local/opt/opencv3/include`(actually in`/usr/local/Cellar/opencv3/HEAD-c1007c7/include`) and `/usr/local/Cellar/boost/1.63.0/include/boost`, they are homebrew's directory. 

Is this error because my installation directory is not appropriate?
